//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson1_EF_Insert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolumler
    {
        public int BolumlerId { get; set; }
        public string BolumAdi { get; set; }
        public short Kontejan { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
