//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson1_EF_Insert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siniflar
    {
        public int SiniflarId { get; set; }
        public string SinifAdi { get; set; }
        public int BolumId { get; set; }
        public string Aciklama { get; set; }
        public int EgitmenId { get; set; }
    }
}
